
services:
  cleanarchitecturedb:
    image: postgres:16.0
  
  cleanarchitectureapi:
    image: ${DOCKER_REGISTRY-}cleanarchitectureapi
    build:
      context: .
      dockerfile: src/CleanArchitecture/CleanArchitecture.Api/Dockerfile